<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>WiiCompiled.Setup.MacOS</AssemblyName>
    <Version>0.2.27</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../WiiCompiled.Setup.Common/WiiCompiled.Setup.Common.csproj" />
    <Compile Include="../WiiCompiled.Setup.Windows/CompileInputsFingerprint.cs" Link="CompileInputsFingerprint.cs" />
  </ItemGroup>
</Project>
